services:
  api-web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 443
    environment:
      - REDIS_URL=redis://fila-redis:6379/0
    ports:
      - "443:443"
    depends_on:
      - fila-redis

  processador-worker:
    build: .
    command: celery -A worker.app_celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://fila-redis:6379/0
    depends_on:
      - fila-redis

  fila-redis:
    image: redis:alpine
